FROM iqgeoproddev.azurecr.io/platform-base:7.4 as extractor
ARG MODULE
ARG VERSION
ARG CUTPATH

# Add the module tarball and extract it
ADD ${CUTPATH}/${VERSION}/IQGeo_${MODULE}_${VERSION}.tar.gz /opt/iqgeo/platform/WebApps/myworldapp/modules/

# Optional: Add language packs if they exist
# ADD ${MODULE}/${SHORTENED_VERSION}/languagepacks /opt/iqgeo/platform/WebApps/myworldapp/modules/${MODULE}/public/locales/

FROM scratch as final

# Copy the extracted module to the final image
COPY --from=extractor /opt/iqgeo/platform/WebApps/myworldapp/modules/${MODULE} /${MODULE}/
